/**
 * Copyright (C) 2022-2023 Agence du Numérique en Santé (ANS) (https://esante.gouv.fr)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * psc-api-maj-v2
 * API CRUD for Personnels et Structures de santé
 *
 * OpenAPI spec version: 1.0
 * Contact: superviseurs.psc@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.pscload.model;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@EqualsAndHashCode
@ToString
@Getter
@Setter
public class ProcessInfo implements Serializable{
  private static final long serialVersionUID = 1L;
  
  
  @JsonProperty("processId")
  private String processId;

  @JsonProperty("createdOn")
  private String createdOn;
  
  @JsonProperty("state")
  private String state;
  
  @JsonProperty("psToCreate")
  private Integer psToCreateCount;

  @JsonProperty("psToCreateIds")
  private List<String> psToCreateIds;
  
  @JsonProperty("psToUpdate")
  private Integer psToUpdateCount;

  @JsonProperty("psToUpdateIds")
  private List<String> psToUpdateIds;
  
  @JsonProperty("psToDelete")
  private Integer psToDeleteCount;

  @JsonProperty("psToDeleteIds")
  private List<String> psToDeleteIds;

  @JsonProperty("downloadedFileName")
  private String downloadedFileName;

  @JsonProperty("extractFileName")
  private String extractFileName;

  @JsonProperty("lockedSerializedFileName")
  private String lockedSerializedFileName;

}
