/*
 * psc-api-maj-v2
 * API CRUD for Personnels et Structures de santé
 *
 * OpenAPI spec version: 1.0
 * Contact: superviseurs.psc@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import fr.ans.psc.model.StructureRef;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Situation d exercice
 */
@Schema(description = "Situation d exercice")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-30T08:44:48.497Z[GMT]")
public class WorkSituation implements Serializable {
    private static final long serialVersionUID = 1L;
    @JsonProperty("situId")
    private String situId = null;

    @JsonProperty("modeCode")
    private String modeCode = null;

    @JsonProperty("activitySectorCode")
    private String activitySectorCode = null;

    @JsonProperty("pharmacistTableSectionCode")
    private String pharmacistTableSectionCode = null;

    @JsonProperty("roleCode")
    private String roleCode = null;

    @JsonProperty("registrationAuthority")
    private String registrationAuthority = null;

    @JsonProperty("structures")
    private List<StructureRef> structures = null;

    public WorkSituation situId(String situId) {
        this.situId = situId;
        return this;
    }

    /**
     * Get situId
     *
     * @return situId
     **/
    @Schema(description = "")
    public String getSituId() {
        return situId;
    }

    public void setSituId(String situId) {
        this.situId = situId;
    }

    public WorkSituation modeCode(String modeCode) {
        this.modeCode = modeCode;
        return this;
    }

    /**
     * Get modeCode
     *
     * @return modeCode
     **/
    @Size(min = 1)
    @Schema(description = "")
    public String getModeCode() {
        return modeCode;
    }

    public void setModeCode(String modeCode) {
        this.modeCode = modeCode;
    }

    public WorkSituation activitySectorCode(String activitySectorCode) {
        this.activitySectorCode = activitySectorCode;
        return this;
    }

    /**
     * Get activitySectorCode
     *
     * @return activitySectorCode
     **/
    @Schema(description = "")
    public String getActivitySectorCode() {
        return activitySectorCode;
    }

    public void setActivitySectorCode(String activitySectorCode) {
        this.activitySectorCode = activitySectorCode;
    }

    public WorkSituation pharmacistTableSectionCode(String pharmacistTableSectionCode) {
        this.pharmacistTableSectionCode = pharmacistTableSectionCode;
        return this;
    }

    /**
     * Get pharmacistTableSectionCode
     *
     * @return pharmacistTableSectionCode
     **/
    @Schema(description = "")
    public String getPharmacistTableSectionCode() {
        return pharmacistTableSectionCode;
    }

    public void setPharmacistTableSectionCode(String pharmacistTableSectionCode) {
        this.pharmacistTableSectionCode = pharmacistTableSectionCode;
    }

    public WorkSituation roleCode(String roleCode) {
        this.roleCode = roleCode;
        return this;
    }

    /**
     * Get roleCode
     *
     * @return roleCode
     **/
    @Schema(description = "")
    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public WorkSituation registrationAuthority(String registrationAuthority) {
        this.registrationAuthority = registrationAuthority;
        return this;
    }

    /**
     * Get registrationAuthority
     *
     * @return registrationAuthority
     **/
    @Schema(description = "")
    public String getRegistrationAuthority() {
        return registrationAuthority;
    }

    public void setRegistrationAuthority(String registrationAuthority) {
        this.registrationAuthority = registrationAuthority;
    }

    public WorkSituation structures(List<StructureRef> structures) {
        this.structures = structures;
        return this;
    }

    public WorkSituation addStructuresItem(StructureRef structuresItem) {
        if (this.structures == null) {
            this.structures = new ArrayList<StructureRef>();
        }
        this.structures.add(structuresItem);
        return this;
    }

    /**
     * Get structures
     *
     * @return structures
     **/
    @Valid
    @Schema(description = "")
    public List<StructureRef> getStructures() {
        return structures;
    }

    public void setStructures(List<StructureRef> structures) {
        this.structures = structures;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkSituation workSituation = (WorkSituation) o;
        return Objects.equals(this.situId, workSituation.situId) &&
                Objects.equals(this.modeCode, workSituation.modeCode) &&
                Objects.equals(this.activitySectorCode, workSituation.activitySectorCode) &&
                Objects.equals(this.pharmacistTableSectionCode, workSituation.pharmacistTableSectionCode) &&
                Objects.equals(this.roleCode, workSituation.roleCode) &&
                Objects.equals(this.registrationAuthority, workSituation.registrationAuthority) &&
                Objects.equals(this.structures, workSituation.structures);
    }

    @Override
    public int hashCode() {
        return Objects.hash(situId, modeCode, activitySectorCode, pharmacistTableSectionCode, roleCode, registrationAuthority, structures);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WorkSituation {\n");

        sb.append("    situId: ").append(toIndentedString(situId)).append("\n");
        sb.append("    modeCode: ").append(toIndentedString(modeCode)).append("\n");
        sb.append("    activitySectorCode: ").append(toIndentedString(activitySectorCode)).append("\n");
        sb.append("    pharmacistTableSectionCode: ").append(toIndentedString(pharmacistTableSectionCode)).append("\n");
        sb.append("    roleCode: ").append(toIndentedString(roleCode)).append("\n");
        sb.append("    registrationAuthority: ").append(toIndentedString(registrationAuthority)).append("\n");
        sb.append("    structures: ").append(toIndentedString(structures)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
